# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'TaskMaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskMaster
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
  pod 'PanModal'
  pod 'CLTypingLabel'
  pod 'TextFieldEffects'
  pod 'lottie-ios'
  pod 'FSCalendar'
end
